# vim: ft=python expandtab

Import('env_gdk')

env_gdk_win32= env_gdk.Clone()
env_gdk_win32['CPPDEFINES']=['HAVE_CONFIG_H',
                       ('G_LOG_DOMAN', '\\\"Gdk\\\"'),
                       'INSIDE_GDK_WIN32',
                       'GDK_COMPILATION'] + env_gdk['DEBUG_CPPDEFINES']
env_gdk_win32.Append(CPPPATH = ['#', '#gdk', '#gdk/win32'])
libgdk_win32_SOURCES = Split("\
	gdkapplaunchcontext-win32.c \
	gdkcolor-win32.c \
	gdkcursor-win32.c \
	gdkdisplay-win32.c \
	gdkdnd-win32.c \
	gdkdrawable-win32.c \
	gdkevents-win32.c \
	gdkfont-win32.c \
	gdkgc-win32.c \
	gdkgeometry-win32.c \
	gdkglobals-win32.c \
	gdkim-win32.c \
	gdkimage-win32.c \
	gdkinput.c \
	gdkinput-win32.c \
	gdkkeys-win32.c \
	gdkmain-win32.c \
	gdkpixmap-win32.c \
	gdkproperty-win32.c \
	gdkscreen-win32.c \
	gdkselection-win32.c \
	gdkspawn-win32.c \
	gdktestutils-win32.c \
	gdkvisual-win32.c \
	gdkwin32id.c \
	gdkwindow-win32.c")

libgdkinclude_HEADERS = "gdkwin32.h"

env_gdk_win32.ParseConfig('pkg-config glib-2.0 --cflags')
env_gdk_win32.StaticLibrary('libgdk-win32', libgdk_win32_SOURCES)

Alias('install', env_gdk_win32.Install("$PREFIX/include/gtk-2.0/gdk", libgdkinclude_HEADERS))
